Add Room Page
dorm-social-room-manager/dsrm-frontend pull request #44
Opened 2023-04-10 18:25 UTC by 235923

closes #26

2023-04-25 02:00 UTC, kaczor6418 requested changes

2023-04-25 02:00 UTC, kaczor6418 commented on src/components/AddRoomForm/AddRoomForm.tsx
> +                    required
This should be time no date
![Screenshot from 2023-04-25 13-54-09](https://user-images.githubusercontent.com/34687242/234155433-234e9588-87cc-4b8d-ba0a-c2ad5f94212e.png)

2023-04-25 02:00 UTC, kaczor6418 commented on src/pages/AddRoomPage.tsx
> +];
`USERS` should be fetched from backend

2023-04-25 02:00 UTC, kaczor6418 commented on src/components/AddRoomForm/AddRoomForm.tsx
> +      }}
this should send a request to backend

2023-06-10 09:54 UTC, macszl requested changes

2023-06-10 09:54 UTC, macszl commented on src/components/AddRoomForm/AddRoomForm.module.scss
> +.input {
We should be using styled components instead of scss

2023-07-06 13:37 UTC, kaczor6418 commented
Closing as commits are fixed in #60

2023-07-06 13:37 UTC, closed without merging